packages:
  - "packages/*"
  - "apps/*"
  - "apps/examples/*"

catalog:
  "@biomejs/biome": "^2.3.7"
  "@observablehq/framework": "^1.13.3"
  "@statewalker/webrun-files": "^0.7.0"
  "@statewalker/webrun-files-mem": "^0.7.0"
  "@statewalker/webrun-files-node": "^0.7.0"
  "@types/node": "^24.10.1"
  "@vitest/browser": "^4.0.12"
  "@vitest/browser-playwright": "^4.0.12"
  "@vitest/coverage-v8": "^4.0.12"
  playwright: "^1.50.0"
  pnpm: "^10.23.0"
  rimraf: "^6.1.2"
  rolldown: "^1.0.0-beta.51"
  tsx: "^4.0.0"
  turbo: "^2.0.0"
  typescript: "^5.6.0"
  vitest: "^4.0.12"
